services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CI=${CI:-false}
        - LINT=${LINT:-false}
    container_name: my-app
    ports:
      - "5173:5173" 
    volumes:
      - ./my-app:/app # mount local 'my-app' to /app inside the container
    environment:
      - NODE_ENV=development  # set environment variable to development
    command: npm run dev
    stdin_open: true  # interactive sessions
    tty: true  # keep the container running interactively
