include:
  - "assets/images/favicon.ico"

theme: jekyll-theme-minimal
logo: "/assets/images/favicon.png"
favicon: "/assets/images/favicon.png"
title: "Find my next course - by Inference"
description: "Find My Next Course is a web application designed to help students explore KTH’s course offerings"